<a href="https://colab.research.google.com/github/amnak004/flyrank-internship/blob/main/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/amnak004/flyrank-internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

Scoring

The goal is to predict a content performance score using historical content features such as CTR, average position, engagement rate, search volume, and competition. The score helps identify which content should be refreshed or prioritized.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Target or proxy

**Target:** Content performance score.

**Proxy:** Existing engagement metrics such as CTR, engagement rate, average position, and traffic indicators. These values are observed from historical content performance rather than manually assigned.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
df[["ctr", "avg_position", "engagement_rate", "trend_pct"]].head()

    ctr  avg_position  engagement_rate  trend_pct
0  0.76          10.6             5.88      -41.4
1  0.05          20.3             0.00      -57.7
2  0.09          36.5             0.00      -60.9
3  0.49           6.2             1.28      -13.8
4  0.13          44.0             0.00      -34.7

In [ ]:
df["target_score"] = (
    (df["ctr"] * 0.4) +
    (df["engagement_rate"] * 0.4) -
    (df["avg_position"] * 0.2)
)

df[["ctr", "engagement_rate", "avg_position", "target_score"]].head()

    ctr  engagement_rate  avg_position  target_score
0  0.76             5.88          10.6         0.536
1  0.05             0.00          20.3        -4.040
2  0.09             0.00          36.5        -7.264
3  0.49             1.28           6.2        -0.532
4  0.13             0.00          44.0        -8.748

## 3. Success metric


The success metric will be Mean Absolute Error (MAE). A lower MAE means the predicted score is closer to the observed content performance and is more useful for decision making.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
df[["ctr", "avg_position", "engagement_rate", "trend_pct"]].describe()

                ctr  avg_position  engagement_rate     trend_pct
count  30000.000000   30000.00000     30000.000000  26612.000000
mean       0.510733      16.34238         2.534520     -4.785969
std        3.279162      15.21679         8.310096    473.861780
min        0.000000       0.00000         0.000000   -100.000000
25%        0.000000       6.20000         0.000000    -62.600000
50%        0.070000      10.80000         0.000000    -33.500000
75%        0.290000      22.30000         1.350000      0.000000
max      100.000000     245.00000       100.000000  44900.000000

## 4. The unit of analysis, as a real dataframe


One row represents one content item (one article or page) with its SEO, traffic, engagement, and content-related features.

## 5. Why ML beats a fixed rule here



Content performance depends on many interacting factors including search volume, competition, CTR, engagement rate, average position, content length, and user behavior. A fixed rule cannot accurately combine these signals, while a machine learning model can learn complex patterns from historical data and provide better decision support.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
df[["search_volume",
    "competition",
    "ctr",
    "avg_position",
    "engagement_rate",
    "trend_pct"]].head()

   search_volume  competition   ctr  avg_position  engagement_rate  trend_pct
0           10.0         0.67  0.76          10.6             5.88      -41.4
1           90.0         0.01  0.05          20.3             0.00      -57.7
2            0.0         0.00  0.09          36.5             0.00      -60.9
3           10.0         0.00  0.49           6.2             1.28      -13.8
4            0.0         0.00  0.13          44.0             0.00      -34.7

## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.